set(_CATKIN_CURRENT_PACKAGE "realsense_launch")
set(realsense_launch_VERSION "0.0.0")
set(realsense_launch_MAINTAINER "afonso <afonso@todo.todo>")
set(realsense_launch_PACKAGE_FORMAT "2")
set(realsense_launch_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(realsense_launch_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(realsense_launch_BUILDTOOL_DEPENDS "catkin")
set(realsense_launch_BUILDTOOL_EXPORT_DEPENDS )
set(realsense_launch_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(realsense_launch_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(realsense_launch_TEST_DEPENDS )
set(realsense_launch_DOC_DEPENDS )
set(realsense_launch_URL_WEBSITE "")
set(realsense_launch_URL_BUGTRACKER "")
set(realsense_launch_URL_REPOSITORY "")
set(realsense_launch_DEPRECATED "")